spring:
  application:
    name: pocmiddleware
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testjava
    redis:
      host: localhost
      port: 6379
azure:
  servicebus:
    connection-string:
uappi-settings:
  hub:
    url: "https://omni.wapstore.com.br/omni-api/v1"
    app-token: ""
    sellers:
      "":
        keys:
          api-key: ""
          secret-key: ""
  platform:
    url: "https://app.mobiis.uappi.dev.br/api/v2"
    app-token: ""
    keys:
      api-key: ""
      secret-key: ""
integration-settings:
  updateStock:
    queueName: ""
    timerPeriod: 6000
    type: "STOCKUPDATE"
    batchLimit: 100
  updateProductPrice:
    queueName: ""
    timerPeriod: 6000
    type: "PRODUCTPRICEUPDATE"
    batchLimit: 100
  updateOrderStatus:
    queueName: ""
    timerPeriod: 1000
    type: "UPDATEORDERSTATUS"
    batchLimit: 1
  updateRetailerCredit:
    queueName: ""
    timerPeriod: 4000
    type: "UPDATERETAILERCREDIT"
    batchLimit: 1
    hash: "credito"
  saveRecommendationList:
    queueName: ""
    timerPeriod: 1000
    type: "WISHLISTINTEGRATION"
    batchLimit: 1
resilience4j:
  circuitbreaker:
    instances:
      circuit-breaker-default:
        sliding-window-size: 3
        failure-rate-threshold: 60
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 60
        permitted-number-of-calls-in-half-open-state: 3
        record-exception:
          - feign.FeignException
          - com.azure.core.exception.HttpRequestException
          - java.lang.Exception
      circuit-breaker-half-open:
        sliding-window-size: 3
        failure-rate-threshold: 20
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 60
        permitted-number-of-calls-in-half-open-state: 3
        record-exception:
          - feign.FeignException
          - com.azure.core.exception.HttpRequestException
          - java.lang.Exception
  retry:
    instances:
      retry-policy:
        max-attempts: 5
        wait-duration: 2
        retry-exception:
          - feign.FeignException
          - com.azure.core.exception.HttpRequestException